//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXeBusPhuongTrang_65134257.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichChay()
        {
            this.Chuyens = new HashSet<Chuyen>();
        }
    
        public int MaLichChay { get; set; }
        public int MaTuyen { get; set; }
        public int MaXe { get; set; }
        public int MaTaiXe { get; set; }
        public System.TimeSpan GioKhoiHanh { get; set; }
        public System.TimeSpan GioDen { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chuyen> Chuyens { get; set; }
        public virtual TaiXe TaiXe { get; set; }
        public virtual Tuyen Tuyen { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
