//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXeBusPhuongTrang_65134257.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int MaTT { get; set; }
        public int MaVe { get; set; }
        public decimal SoTien { get; set; }
        public string PhuongThuc { get; set; }
        public System.DateTime ThoiGianThanhToan { get; set; }
        public string TrangThai { get; set; }
    
        public virtual Ve Ve { get; set; }
    }
}
