//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLXeBusPhuongTrang_65134257.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tuyen()
        {
            this.LichChays = new HashSet<LichChay>();
        }
    
        public int MaTuyen { get; set; }
        public string TenTuyen { get; set; }
        public int BenDau { get; set; }
        public int BenCuoi { get; set; }
        public Nullable<int> QuangDuongKm { get; set; }
    
        public virtual BenXe BenXe { get; set; }
        public virtual BenXe BenXe1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichChay> LichChays { get; set; }
    }
}
